### ISSUE TITLE
A TODO List

### ISSUE THREAD

**Issue by vorugantia** [vorugantia/asist-env#1]
Specific Implementation:

- [x] Add is_open as an arg in `PortalNode` `__init__()` function. 

- [x] And is_open to the portal data file.

- [x] Connect Portal with portals

- [ ] Add Light Turning, and its observation ("The room is dark") and action ("I need to turn on the light")

- [ ] Some portal to portal transitions could be blocked by rubble and/or fire.

- [ ] Random Graph: Change Victim random range to a geometric distribution

- [ ] Better Layout: Resolve portal Nodes Collision

- [x] ~~Vanilla Q-Learning with global observation space and action space~~

- [x] ~~Vanilla Q-Learning with narrow action space~~

RL Model Development:

- [ ] Documentation

- [ ] Animation for Episodes

- [x] Reformat Observation Space, and action space

- [ ] Give a reward to the agent if it all victims are saved earlier

- [ ] Try RL models here: [Stable Baselines docs](https://stable-baselines.readthedocs.io/en/master/)

- [ ] Proximal Policy Optimization

- [ ] Deep Q-Learning

- [ ] Deep Q-Learning: Target Network

- [ ] Try Different Reward, also gamma decay

- [ ] Literature Review: the best way to incorporate time into reinforcement Learning

Need Discussion:

- [x] Standardize CSV format - talk with Jincheng and Rajay

- [x] Discuss a proper way of formating action space and observation space
[Quora: How do you deal with action space of varying size in reinforcement learning?](https://www.quora.com/How-do-you-deal-with-action-space-of-varying-size-in-reinforcement-learning-In-poker-for-instance-the-set-of-legal-actions-depends-on-which-part-of-the-game-youre-in-flop-river-etc-How-do-you-design-the-neural)
[StackExchange: Inconsistent action space in Reinforcement Learning
](https://ai.stackexchange.com/questions/9491/inconsistent-action-space-in-reinforcement-learning)

General TODO:

- [x] Animation for agent moves given CSV or JSON file.

- [ ] Realtime update of the graph visualization when agent plays. (console_play, graphic for reinforcement learning)

- [ ] Agent Class, with speed (Player Skill), its own graph representing its memory, brain

- [x] Random Graph Generation. (Generate connected rooms, add portals, add victims, link them)
[Networkx Random Graph](https://networkx.github.io/documentation/stable/reference/generators.html#module-networkx.generators.random_graphs)

- [x] A better graph layout visualization (no collision)

- [ ] Make a graph representation for Falcon map
